### ISSUE TITLE
Status nagrody

### ISSUE THREAD

**Issue by bohatertygodnia** [roselew/bohater2#2]
trzy typy nagród:
- unused
- chosen
- received
i to zapisujemy w jsonie pod obiektem status

Po fetch sprawdzamy czy możemy odebrać nagrodę - sprawdzamy listę punktów 

W oknie nagrody wyświetlamy je w kolejności
- unused but available
- other unused 
- chosen z dopiskiem czekamy na Twojego rodzica
- reveived z dopiskiem dostałeś już takie nagrody

**Comment by bohatertygodnia** [comment]
Tylko brakuje informacji kiedy nagrodę odebraliśmy

**Comment by bohatertygodnia** [comment]
Odejmujemy punkty gdy jest chosen 
Więc potrzebujemy jeszcze pola chosenDate ??

**Comment by roselew** [comment]
Wykonane
